version: '3'
services:
  web:
    image: nginx:1.15.8
    ports:
      - "8000:80"
    depends_on:
      - ap
    volumes:
      - ./server/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  ap:
    build: ./docker/ap
    depends_on:
      - db
    volumes:
      - ./server/ap/application:/var/www/html
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bbc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./server/db/var/lib/mysql:/var/lib/mysql



