version: '3'
services:
  web:
    image: nginx:1.21
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ./docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
